Repository anything-market/don-t-buy-macat, pull requests merged in 2022-07, with the labels that each got.

#11 404Page UI 구현
  src/components/error/Error.jsx
  src/components/error/error.style.jsx
Labels: feat✨

#12 feat: 헤더 컴포넌트 UI 구현
  src/components/header/BasicHeader/BasicHeader.jsx
  src/components/header/BasicHeader/basicHeader.style.jsx
  src/components/header/ChatHeader/ChatHeader.jsx
  src/components/header/ChatHeader/chatHeader.style.jsx
  src/components/header/MainHeader/MainHeader.jsx
  src/components/header/MainHeader/mainHeader.style.jsx
  src/components/header/SearchHeader/SearchHeader.jsx
  src/components/header/SearchHeader/searchHeader.style.jsx
  src/components/header/UploadHeader/UploadHeader.jsx
  src/components/header/UploadHeader/uploadHeader.style.jsx
Labels: feat✨

#14 feat: 피드(Home) 컴포넌트 구현
  src/components/post/PostAuthor/PostAuthor.jsx
  src/components/post/PostAuthor/PostAuthor.style.jsx
  src/components/post/PostCard/PostCard.jsx
  src/components/post/PostCard/PostCard.style.jsx
  src/components/post/PostContent/PostContent.jsx
  src/components/post/PostContent/PostContent.style.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.style.jsx
Labels: feat✨

#18 feat: 게시글 댓글 페이지 컴포넌트 구현
  src/components/comment/CommentCard.jsx
  src/components/comment/CommentList/CommentList.jsx
  src/components/comment/CommentList/commentList.style.jsx
  src/components/comment/CommentReply/CommentReply.jsx
  src/components/comment/CommentReply/commentReply.style.jsx
Labels: feat✨

#31 feat: 헤더 컴포넌트 모달, alert창 UI 추가
  src/components/header/BasicHeader/BasicHeader.jsx
  src/components/header/BasicHeader/basicHeader.style.jsx
  src/components/header/ChatHeader/ChatHeader.jsx
  src/components/modal/Modal/Modal.jsx
  src/components/modal/Modal/modal.style.jsx
  src/components/modal/ModalBtn/ModalBtn.jsx
  src/components/modal/ModalBtn/modalBtn.style.jsx
  src/components/modal/alert/LogoutAlert/LogoutAlert.jsx
  src/components/modal/alert/PostDeleteAlert/PostDeleteAlert.jsx
  src/components/modal/alert/commonAlert.style.jsx
  src/components/modal/modalContent/BasicModalContent/BasicModalContent.jsx
  src/components/modal/modalContent/ChatModalContent/ChatModalContent.jsx
  src/components/modal/modalContent/CommentModalContent/CommentModalContent.jsx
  src/components/modal/modalContent/PostModalContent/PostModalContent.jsx
Labels: feat✨, refactor💪, design👗

#32 feat: 게시물 작성 페이지 UI구현
  src/components/postUpload/PostUpload.jsx
  src/components/postUpload/postUpload.style.jsx
Labels: feat✨

#36 feat: user 컴포넌트 UI 구현 및 팔로우 버튼 컴포넌트화
  src/components/button/FollowBtn/FollowBtn.jsx
  src/components/button/FollowBtn/followBtn.style.jsx
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
Labels: feat✨

#39 feat: 로그인기능 구현
  src/components/login/Login.jsx
  src/components/login/login.style.jsx
Labels: feat✨

#37 feat: 회원가입 이메일/비밀번호 유효성검사 기능구현
  src/components/sign-in/SetProfile.jsx
  src/components/sign-in/SignIn.jsx
  src/components/sign-in/signin.style.jsx
  src/pages/Pages.jsx
Labels: feat✨

#40 feat: 검색 페이지 기능 구현
  src/components/header/MainHeader/MainHeader.jsx
  src/components/header/SearchHeader/SearchHeader.jsx
  src/components/search/SearchUserList/SearchUserList.jsx
  src/components/userComponent/UserComponent.jsx
  src/pages/search/Search.jsx
Labels: feat✨

#43 [feat] 게시글 이미지 미리보기 기능구현
  src/components/postUpload/PostUpload.jsx
  src/components/postUpload/postUpload.style.jsx
Labels: feat✨, design👗

#47 Feature/adoption post page UI
  src/components/adoptPost/AdoptPost.jsx
  src/components/adoptPost/adoptPost.style.jsx
  src/components/header/BasicHeader/BasicHeader.jsx
  src/components/header/BasicHeader/basicHeader.style.jsx
  src/components/header/ChatHeader/ChatHeader.jsx
  src/components/header/ChatHeader/chatHeader.style.jsx
  src/components/header/MainHeader/MainHeader.jsx
  src/components/header/MainHeader/mainHeader.style.jsx
  src/components/header/SearchHeader/SearchHeader.jsx
  src/components/header/SearchHeader/searchHeader.style.jsx
  src/components/header/UploadHeader/UploadHeader.jsx
  src/components/header/UploadHeader/uploadHeader.style.jsx
  src/components/header/commonHeader.style.jsx
Labels: feat✨, design👗

#46 feat: 로그인 기능 구현
  src/components/login/Login.jsx
  src/components/sign-in/SignIn.jsx
Labels: bug🐞, feat✨

#50 [feat] 스플래쉬 UI 구현
  src/assets/catLogo.svg
  src/assets/catLogoStar.svg
  src/assets/catLogoTxt.svg
  src/components/splash/Splash.jsx
  src/components/splash/splash.style.jsx
Labels: feat✨, help wanted🧐

#53 [design] Search페이지 검색결과 스타일 수정
  src/pages/search/Search.jsx
  src/pages/search/Search.style.jsx
Labels: design👗

#54 [Refactor] Home에서 로그인 데이터 token으로 받아오도록 수정 및 주석 삭제
  src/components/follow/FollowContainer/FollowContainer.jsx
  src/components/follow/FollowContainer/FollowContainer.style.jsx
  src/components/header/FollowHeader/Followheader.jsx
  src/components/header/FollowHeader/Followheader.style.jsx
  src/components/post/PostContent/PostContent.jsx
  src/components/userComponent/UserComponent.jsx
  src/pages/Pages.jsx
  src/pages/follow/Follow.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.style.jsx
Labels: refactor💪

#59 feat: 고양이 입양 등록 페이지 기능 구현
  src/components/adoptPost/AdoptPost.jsx
  src/pages/Pages.jsx
  src/pages/adoptPost/AdoptPost.jsx
  src/pages/adoptPost/Regex.jsx
  src/pages/adoptPost/ValidationInput.jsx
  src/pages/adoptPost/adoptPost.style.jsx
Labels: bug🐞, feat✨, fix🛠

#63 [Refactor] 로그인 데이터 token 받아오도록 수정
  src/components/comment/CommentCard.jsx
Labels: refactor💪

#62 feat: 피드 내 이미지 슬라이드 구현
  src/components/post/PostContent/PostContent.jsx
  src/components/post/PostContent/PostContent.style.jsx
  src/components/post/PostImgContainer/PostImgContainer.jsx
  src/components/post/PostImgContainer/PostImgContainer.style.jsx
Labels: feat✨

#65 [feat] 피드 내 '좋아요' 버튼 클릭 기능 구현
  src/assets/icon-heart.svg
  src/components/button/HeartBtn/HeartBtn.jsx
  src/components/button/HeartBtn/HeartBtn.style.jsx
Labels: feat✨

#66 feat: 하단 네비게이션 바 구현
  src/components/navigation-bar/NavigationBar.jsx
  src/pages/home/Home.jsx
Labels: feat✨

#70 [feat] 게시글 상세페이지 화면 구현
  src/components/comment/CommentCard.jsx
  src/components/comment/CommentReply/CommentReply.jsx
  src/components/post/PostCard/PostCard.jsx
  src/pages/Pages.jsx
  src/pages/home/Home.jsx
  src/pages/post/Post.jsx
Labels: feat✨, design👗

#64 [feat] 게시글 작성페이지 업로드 기능구현
  src/components/postUpload/PostUpload.jsx
Labels: feat✨

#74 [feat] 사용자 프로필 페이지 UI 구현 및 프로필 기능 구현
  src/assets/message-circle.svg
  src/components/adoptSection/AdoptSection.jsx
  src/components/button/FollowBtn/FollowBtn.jsx
  src/components/navigation-bar/NavigationBar.jsx
  src/components/profile/ProfileInfo/ProfileInfo.jsx
  src/components/profile/ProfileInfo/ProfileInfo.style.jsx
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
  src/pages/Pages.jsx
  src/pages/userProfile/UserProfile.jsx
  src/pages/userProfile/UserProfile.style.jsx
Labels: feat✨

#73 [refactor] 게시글 관련 컴포넌트 및 Home 컴포넌트 리팩토링
  src/components/post/PostCard/PostCard.jsx
  src/components/post/PostCard/PostCard.style.jsx
  src/components/post/PostContent/PostContent.jsx
  src/components/post/PostContent/PostContent.style.jsx
  src/pages/home/Home.jsx
Labels: refactor💪

#72 feat: 소셜로그인 기능 구현
  src/assets/full-logo.svg
  src/components/login/SocialLogin.jsx
  src/pages/Pages.jsx
Labels: feat✨

#78 feat: 채팅, 채팅 목록 페이지 UI 구현
  src/components/header/ChatHeader/ChatHeader.jsx
  src/components/header/commonHeader.style.jsx
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
  src/pages/Pages.jsx
  src/pages/chats/Chat/Chat.jsx
  src/pages/chats/Chat/chat.style.jsx
  src/pages/chats/ChatList/ChatList.jsx
  src/pages/chats/ChatList/chatList.style.jsx
  src/pages/chats/TestUserInfo.jsx
Labels: feat✨, help wanted🧐, fix🛠

#79 [feat] 게시글 상세페이지 본문 컴포넌트 취합
  src/components/comment/CommentCard.jsx
  src/components/post/PostAuthor/PostAuthor.jsx
  src/components/post/PostAuthor/PostAuthor.style.jsx
  src/components/post/PostCard/PostCard.jsx
  src/components/post/PostCard/PostCard.style.jsx
  src/components/profile/ProfileInfo/ProfileInfo.jsx
  src/components/userComponent/UserComponent.jsx
  src/pages/post/Post.jsx
  src/pages/userProfile/UserProfile.jsx
  src/pages/userProfile/UserProfile.style.jsx
Labels: feat✨

#81 [bug] nav 스타일로 인한 오류 수정
  src/components/navigation-bar/NavigationBar.jsx
  src/pages/chats/ChatList/ChatList.jsx
Labels: bug🐞

#82 design: 입양 등록 페이지 헤더와 간격 조정
  src/pages/adoptPost/adoptPost.style.jsx
Labels: bug🐞, design👗

#83 design: 로고위치정렬 및 카카오이미지 복구
  src/assets/message-circle.svg
  src/components/login/SocialLogin.jsx
  src/components/login/socialLogin.style.jsx
Labels: bug🐞, design👗

#84 fix: 컨텐츠 하단부 네비바에 가려지는 현상 해결
  src/pages/chats/ChatList/chatList.style.jsx
  src/pages/userProfile/UserProfile.style.jsx
Labels: bug🐞

#85 [fix] navbar에서 '프로필' 버튼 클릭 시 로그인 전의 프로필이 뜨는 버그 수정
  src/components/navigation-bar/NavigationBar.jsx
Labels: bug🐞

#86 [feat] 스플래쉬 UI 구현 (이동 화면 수정)
  src/pages/Pages.jsx
  src/pages/splashMain/SplashMain.jsx
  src/pages/upload/Upload.jsx
  src/utils/isLogin.js
Labels: feat✨

#88 [refactor] 에러페이지 라우터 추가, 색상변경
  src/components/error/error.style.jsx
  src/pages/Pages.jsx
Labels: refactor💪

#92 [feat] 게시물 업로드, 댓글 컴포넌트 프로필 사진 추가
  src/components/comment/CommentList/CommentList.jsx
  src/components/comment/CommentList/commentList.style.jsx
  src/components/comment/CommentReply/CommentReply.jsx
  src/components/comment/CommentReply/commentReply.style.jsx
  src/components/postUpload/PostUpload.jsx
  src/components/postUpload/postUpload.style.jsx
Labels: feat✨

#89 [feat] '팔로우' 버튼 클릭 기능 구현
  src/components/button/FollowBtn/FollowBtn.jsx
  src/components/follow/FollowContainer/FollowContainer.jsx
  src/components/follow/FollowUser/FollowUser.jsx
  src/components/follow/FollowUser/FollowUser.stlye.jsx
  src/components/follow/FollowUserList/FollowUserList.jsx
  src/components/profile/ProfileInfo/ProfileInfo.jsx
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
  src/pages/Pages.jsx
  src/pages/follow/Follow.jsx
  src/pages/userProfile/UserProfile.jsx
Labels: feat✨

#90 [bug] 다른 사용자의 프로필 페이지에서 하단 '프로필'을 클릭했을 때 화면이 바뀌지 않는 이슈
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
  src/pages/userProfile/UserProfile.jsx
Labels: bug🐞

#94 [refactor] 댓글작성페이지, 게시물작성 페이지 주석제거
  src/components/comment/CommentList/commentList.style.jsx
  src/components/postUpload/PostUpload.jsx
Labels: refactor💪

#96 [bug, refactor] 댓글 작성시 실시간 시간 출력
  src/components/comment/CommentList/CommentList.jsx
  src/utils/timeForToday.js
Labels: bug🐞, fix🛠

#98 [refactor] 댓글 리스트 토글 버튼, 모달 컴포넌트 추가
  src/components/comment/CommentList/CommentList.jsx
  src/components/comment/CommentList/commentList.style.jsx
Labels: refactor💪, design👗

#99 [feat] 피드 게시글 내 날짜 년/월/일 형식으로 표기
  src/components/post/PostCard/PostCard.style.jsx
  src/components/post/PostContent/PostContent.jsx
  src/pages/home/Home.style.jsx
Labels: feat✨

#100 [feat] 사용자 프로필 페이지 하단 피드 내 앨범형 피드 구현
  src/components/post/PostAlbumCard/PostAlbumCard.jsx
  src/components/post/PostAlbumCard/PostAlbumCard.style.jsx
  src/pages/userProfile/UserProfile.jsx
  src/pages/userProfile/UserProfile.style.jsx
Labels: feat✨

#103 chatHeader navigate 경로 chats로 변경
  .firebase/hosting.YnVpbGQ.cache
  src/components/header/ChatHeader/ChatHeader.jsx
Labels: bug🐞

#107 [bug] 404 에러 페이지 연결
  firebase.json
  src/components/postUpload/PostUpload.jsx
Labels: bug🐞

#108 [fix] 게시글 작성 후 내 프로필 페이지로 이동
  src/components/postUpload/PostUpload.jsx
Labels: fix🛠

#109 [fix] profileImage가 default일때 표시되는 이미지 수정
  src/components/sign-in/SetProfile.jsx
Labels: bug🐞

#112 bug: 회원가입 성공시 로그인페이지로 이동/프로필사진 설정시 이미지 찌그러짐 해결
  src/components/login/Login.jsx
  src/components/sign-in/SetProfile.jsx
  src/components/sign-in/SignIn.jsx
Labels: bug🐞

#114 [bug] 이미지업로드 파일 형식 변경
  src/components/postUpload/PostUpload.jsx
Labels: bug🐞

#115 [fix] 게시글 내 이미지, 유저컴포넌트 프로필 이미지 관련 수정
  src/components/post/PostContent/PostContent.jsx
  src/components/post/PostImgContainer/PostImgContainer.jsx
  src/components/post/PostImgContainer/PostImgContainer.style.jsx
  src/components/profile/ProfileInfo/ProfileInfo.style.jsx
  src/components/userComponent/UserComponent.jsx
  src/components/userComponent/userComponent.style.jsx
Labels: fix🛠

#116 [fix] Home 컴포넌트 수정 및 콘솔 삭제
  src/components/comment/CommentReply/CommentReply.jsx
  src/components/header/UploadHeader/UploadHeader.jsx
  src/components/post/PostAlbumCard/PostAlbumCard.jsx
  src/components/postUpload/PostUpload.jsx
  src/pages/home/Home.jsx
  src/pages/userProfile/UserProfile.jsx
Labels: fix🛠

#117 [feat] 게시글 내 이미지 엑박일때 디폴트 이미지로 뜨도록 교체
  src/components/post/PostImgContainer/PostImgContainer.jsx
Labels: feat✨

#118 fix: 입양 등록 후 사용자 페이지로 바로 이동할 수 있도록 수정
  src/pages/adoptPost/AdoptPost.jsx
Labels: bug🐞

#122 fix: 댓글 게시버튼 비활성화 오류 수정
  src/components/comment/CommentReply/CommentReply.jsx
Labels: bug🐞

#124 feat: adoptSection에서 입양 등록 게시물 삭제 기능 구현
  src/components/adoptSection/AdoptSection.jsx
  src/components/modal/alert/PostDeleteAlert/PostDeleteAlert.jsx
  src/components/modal/modalContent/ProductModalContent/ProductModalContent.jsx
Labels: feat✨

#126 feat: 토큰 검증기능 추가
  src/components/login/Login.jsx
Labels: feat✨

#123 [feat] 사용자 프로필 수정 기능 구현
  src/components/profile/ProfileInfo/ProfileInfo.jsx
  src/pages/Pages.jsx
  src/pages/editprofile/EditUserProfile.jsx
  src/pages/editprofile/EditUserProfile.style.jsx
Labels: feat✨

#129 design: 로그인 input창 focus시 border-bottom색 추가
  src/components/login/login.style.jsx
Labels: feat✨, design👗

#134 [feat] favicon 타이틀 추가
  public/favicon.ico
  public/index.html
Labels: feat✨

#136 [refactor] 게시물 업로드 이미지 반응형 적용
  src/components/postUpload/postUpload.style.jsx
Labels: refactor💪, design👗
